### PR TITLE
Fix manifest.toml: `zip = true` -> `format = zip`

### PR DESCRIPTION
**Pull request by Salamandar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by oleole39** [comment]
Change in manifest format?
!testme

**Comment by Salamandar** [comment]
Not sure, for me it was always like that, but I can't be sure.

**Comment by oleole39** [comment]
Did you push this PR due to having a bug at install ? Or for harmonization purpose ?
For sure I did not created the `zip = true` by myself when originally packaging the app and I find it still working so far for some reasons, even though I indeed see [the doc](https://yunohost.org/en/packaging_apps_resources#properties-for-each-sourc) now describes explicitly the `format = zip` option.
If you did not find any bug either, I'll wait for the next app upgrade to combine this PR. Thanks.

**Comment by Salamandar** [comment]
@oleole39 I wrote some tooling to validate the format of the manifest.toml and saw some errors on some apps, so even though it's not a "blocking" issue and doesn't break anything, it's not a valid key ;)

See the schema here : https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

**Pull request merged**
